
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: yaroslavzev

development:
  <<: *default
  database: develop_blog
  
test:
  <<: *default
  database: test_blog

production:
  <<: *default
